homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 50.2263
  longitude: 19.0587
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 279.5
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Warsaw
  # Customization file
  customize: !include customize.yaml
  customize_domain: !include customize_domain.yaml
  customize_glob: !include customize_glob.yaml

# Show links to resources in log and frontend
introduction:

map:

# Enables the frontend
frontend:
  javascript_version: latest

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  base_url: gohm-home.eu:8123
  ssl_certificate: /etc/letsencrypt/live/gohm-home.eu/fullchain.pem
  ssl_key: /etc/letsencrypt/live/gohm-home.eu/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# View all events in a logbook
logbook: !include logbook.yaml

# Track the sun
sun:

zwave:
  usb_path: /dev/ttyACM0
  new_entity_ids: true

climate:
  platform: zwave

arduino:
  port: /dev/ttyUSB0

ffmpeg:

automation: !include automations.yaml
group: !include groups.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
history: !include history.yaml
zone: !include zones.yaml
mqtt: !include mqtt.yaml
device_tracker: !include device_tracker.yaml
light: !include lights.yaml
binary_sensor: !include binary_sensors.yaml
notify: !include notify.yaml
switch: !include switches.yaml
alert: !include alerts.yaml
fan: !include fans.yaml
scene: !include scenes.yaml
google: !include google.yaml
timer: !include timers.yaml
camera: !include camera.yaml
media_player: !include media_player.yaml
#image_processing: !include image_processing.yaml
influxdb: !include influxdb.yaml
input_select: !include input_select.yaml
input_number: !include input_number.yaml
input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml
input_text: !include input_text.yaml
cloud: !include cloud.yaml
shell_command: !include shell_commands.yaml
tts: !include tts.yaml

#frontend: !include frontend.yaml
