- platform: mqtt
  name: "Wentylator w łazience"
  state_topic: "/home/lazienka/wentylator/state"
  command_topic: "/home/lazienka/wentylator"
  optimistic: false
#    qos: 0
  payload_on: "ON"
  payload_off: "OFF"

- platform: xiaomi_miio
  host: 192.168.1.241
  token: !secret xiaomi_miio_token
