- platform: vlc
  arguments: '--alsa-audio-device=hw:1,0'

- platform: spotify
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

- platform: mpd
  host: 192.168.1.101

- platform: mpd
  host: 192.168.1.100
  #port: 6680
  name: MPD Server

- platform: snapcast
  host: 192.168.1.100

#- platform: volumio
#  host: volumio.local
#  port: 3000


#- platform: mpd
#  host: 192.168.1.100
#  location: Server
#- platform: mpd
#  server: 192.168.1.101
#  location: Room 1
